const data = [
  {
    id: 0,
    title: 'Kaswece Online Shop',
    skills: ['HTML', 'CSS', 'React'],
    thumbnail: '/images/kaswece.png',
    liveAdr: 'https://chwonseok.github.io/kaswece/',
    codeAdr: 'https://github.com/chwonseok/kaswece',
    theme: '#e97879',
  },
  {
    id: 1,
    title: 'Apple Calculator',
    skills: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: '/images/apple-calculator.png',
    liveAdr: 'https://chwonseok.github.io/apple_calculator/',
    codeAdr: 'https://github.com/chwonseok/apple_calculator',
    theme: '#FF9A00',
  },
  {
    id: 2,
    title: 'Workout Recorder',
    skills: ['HTML', 'CSS', 'JavaScript', 'Leaflet'],
    thumbnail: '/images/workout-recorder.png',
    liveAdr: 'https://chwonseok.github.io/workout_recorder/',
    codeAdr: 'https://github.com/chwonseok/workout_recorder',
    theme: '#C9DB9F',
  },
  {
    id: 3,
    title: 'Dice Game',
    skills: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: '/images/dice-game.png',
    liveAdr: 'https://chwonseok.github.io/dice_game/',
    codeAdr: 'https://github.com/chwonseok/dice_game',
    theme: '#16BDC0',
  },
  {
    id: 4,
    title: 'Random Number Game',
    skills: ['HTML', 'CSS', 'JavaScript'],
    thumbnail: '/images/random-number-game.png',
    liveAdr: 'https://chwonseok.github.io/random_number_game/',
    codeAdr: 'https://github.com/chwonseok/random_number_game',
    theme: '#222222',
  },
  {
    id: 5,
    title: 'Kakao Clone',
    skills: ['HTML', 'CSS'],
    thumbnail: '/images/kakao-clone.png',
    liveAdr: 'https://chwonseok.github.io/kakao_clone/',
    codeAdr: 'https://github.com/chwonseok/kakao_clone',
    theme: '#FFE812',
  },
];

export default data;
